[package]
name = "CopyCat"
version = "0.1.0"
edition = "2024"

[dependencies]
arboard = "3.4.1"
eframe = "0.31.1"
egui = "0.31.1"
env_logger = "0.11.6"
rdev = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
