on:
  push:
    branches:
      - '**'
  pull_request:
    paths:
      - Cargo.toml
      - Cargo.lock
      - lapce-**

name: CI

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  build:
    name: Rust on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Removed the failing Ubuntu dependency step.
      #- name: Install dependencies on Ubuntu
      #-   if: startsWith(matrix.os, 'ubuntu')
      #-   run: sudo make ubuntu-deps

      - name: Update toolchain & add llvm-tools
        run: rustup update --no-self-update

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Build debug
        run: cargo build --frozen

      - name: Run doc tests
        run: cargo test --doc --workspace

      # Build a release binary for distribution.
      - name: Build release
        run: cargo build --release --frozen

      # Upload the built release artifact.
      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.os }}
          path: target/release/${{ matrix.os == 'windows-latest' ? 'copycat.exe' : 'copycat' }}

  clippy:
    name: Clippy on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Update toolchain & add clippy
        run: |
          rustup update --no-self-update
          rustup component add clippy

      # Removed the failing Ubuntu dependency step.
      #- name: Install dependencies on Ubuntu
      #-   if: startsWith(matrix.os, 'ubuntu')
      #-   run: sudo make ubuntu-deps

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Run clippy
        run: cargo clippy

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    # Run this job only on tag pushes.
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4

      # Download artifacts from all build jobs.
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: release-artifacts

      # Create a GitHub Release and attach the built binaries.
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          files: release-artifacts/**/*

